function readFile(input) {
	let f = input.files[0];
	let reader = new FileReader();
	reader.readAsText(f);
	reader.onload = function() {
		let texte=reader.result.replace(/(?:\r|\n|\r\n)/g, '-');
		totalPriorites(texte)
	};
	reader.onerror = function() {
		console.log(reader.error);
	};
}

function totalPriorites(texte) {
	let sacs=texte.split('-');
	let prioritesSacs=sacs.map(prioriteSac)

	let total=prioritesSacs.reduce(function (accumVariable, curValue) {
		return accumVariable + parseInt(curValue)
		}, 0);
	
	console.log('total',total)
	document.getElementById('reponse').value=total;

	/*2e partie, on fait des groupes de 3 elfes/sacs */
	let total2=0;
	for (let i = 0; i < sacs.length; i+=3) {
		total2+=prioriteBadge(sacs[i],sacs[i+1],sacs[i+2]);
	}	
	console.log('total2',total2)
	document.getElementById('reponse-2').value=total2;

}

function prioriteSac(sac) {
	let taille=sac.length;
	
	let poche1A=sac.split("",taille/2); //tableau
	let poche2=sac.slice(-1*taille/2);//string

	let doublon='';
	poche1A.forEach(function(item) {
		if(poche2.indexOf(item) >= 0 ) {
			//On a trouvé l'item dans la 2e poche
			doublon=item;
		}
	});

	return prioriteItem(doublon);
}

function prioriteItem(item) {
	let priorites='0abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
	return priorites.indexOf(item);
}

function prioriteBadge(sac1,sac2,sac3) {
	let sac1A=sac1.split("");

	let commun='';
	sac1A.forEach(function(item) {
		if(sac2.indexOf(item) >= 0 && sac3.indexOf(item) >= 0) {
			//on a trouvé l'item commun aux 3 sacs
			commun=item;
		}
	})

	return prioriteItem(commun);

}



let temp="lflZfgnSnlmmlgGfjGthQPtLNsQhvbHLLpSS-zrCVDVFMJTCTcCJMwCThWbtbpbWpPbtbHPLQssLsHP-rBFcrwFzFwwVDcDrzTzJfnRGjllBdGZnnZfhqmdn-FjpnFRDmbRtnbJrFJmSTsGShWVhGqGVVsmqs-ZwPvNPdzNZwfzBNLdNNNNcLvhnQhqMTVsTGSWSqGqTdVWhMT-vgLZHfvLffNLPbggnrbFpJnCbC-hzJzGjGfqmGtDQtDSvVV-plpcMBNBcCTlTgCMbvtrsSVsVJDJlrwDQr-McHBMMcTTHgJnWqnRqjzZnnRzR-ppvsGZhDGprrSjSllwfZ-TTFMMFJMgMHmHmdqdSvNqlSSSNJv-mgBPHTRWFRVcpvsVttppbv-ZZDssfMDMtqqppZLLJzmzSTwNJplTSgpgm-BdCRRHFRbccWWBvBHCdcJVngNVSvTgVNzgNNVmnz-QHFFrBdcGtqPmmQh-qLvQFRgLSSNgqQvRrqLTQvLttwDBFWDwjwFttDdlBBwBwM-nbsmZnbmHbZVCGPVmHWtwlStBDtwBMtwWHMj-CnCbhGCPpPCSnZmrgRNRqNRrLNgrzh-vgLWWHRNLnWwLggWzwLFFzMmBMRMhMhTbhsmmsbbmQTm-rScpJJDDpjtSDPPPJDpjqPCHBBtlTdblmmlhBsMMmTsbmtsl-GHZHCPprSSwgvWNVwVZv-dMrCMJMqvtdFwcjczjQzThtm-gGbLblLpZlHvllQhlQwcjT-GHRWvPRbPHPRvNGbvdRBqdqBBfRqBqnrfF-VsHcljlbhmHbHHlcjVcVShJSCdJCfMrMMQDfRNFCfMRGfNrQ-tGtvLtpgBTGvDMMRdMMgdCNM-pnGnGqGtvtzTLjWqmSSjHhWhWs-NJTDntDNDVjNnjBfjjjcCZCZcVqCSCLqcSScCc-zvhgRgQvvdllgQbHghlvHrRHSScBCRqqwCLGqSMCZCGGGqMZ-pvvrHzdgvlgzQphQsDFmnsNTTtjfjJJmPB-ScnSZSZZlmjmHjjWHHWZftJVJpppwtVVnLJtnptnwt-CFFlQBbbPQqrBwJrJJrGJD-PgTqRddFzgdRPFFbFgqQFgsSjfHWfSHmSMWcjZlmZmjTZM-lzBRtctbnBRBRBBWnDnDWjlLVvwGMrvwrHHQHGmDvHQvHGrV-FsTgFCTSgsCNspzhCGMfTHQVwVMfMmMmrH-hSdSFgghhqpRbLqjntqnPz-DCDnNGFFDQdQmVDNdFVNFccpJLHWSvPLrvvvPtGGhSttLv-sBgTzzZqrBlfljslWBhvHSvPBhSBJSSL-lRlTgMzlzrwRrnmbCMCFnNVMnc-MJQJMJHBrsdrHwts-dbbSVGgbjVqGTVfqddCTpmWWcprgNgWmcWwWswpN-LPdGGdVGPCVdLBlBMlDRRRMD-vdcwZLTdTFFRDHVgmpppMmqZ-jGPzCnQPjlsDVqDpqDHbgP-BjWJrlGQQzrCzBzlzBCGBznzwNRNcwLJdwTJFTHRSTvtLcNN-ngrgqTjJJZnjFJpnqnnVTLzBbbHbLQdLHLHbrdHdHG-lNcltCCtvftfWssPbMQdMBzhbbcBDLdh-PRtWsQCmWsmSsCNCSvCSWlspwgqjqmqjTpnJZwnZVpFwgq-PjWjGDCjmrmWPNmvWDWFmgCNfVJRLfJRfLDLJQlfHplpRbfR-MtZMtcSbccZshTtQTVVTpzHlLRRQLV-cZhbwMnwqsqnhnqtMBnvNFrnGPNPPmgPGCgW-WBjWjWjqZwQJnJZCZZbf-StHSDRPHHcTrTrJpLCCMbrqnJn-RvTTvGqcqTFvSvSRDHvRjlhgWBWBdhjwjGgNjhlj-FSbCqcFsbCPtrcrqhCScbshMjHDGGWBLHBnjGLPBHGGBGnHj-flQdlsgQgGnQHBHjDn-vllgRZdmvsvpgdwZgzJdwRmprqccSFcSShJbTSttqMCrCCch-GwwgCtvHgwcHVVDqpWdfnqVv-sllBsSNBjSrLfqhLgjfqhL-ZbQbZQzgQQPSblBggNQRHGZHHCmwmHFGGcwtJm-CmGVGBTVTmmTWTNLLCVgCSFvDQppQQDDnDQDJpMggfnQft-RrtdqtldPbHzRbnjRfQZjJfMDnMj-wcwhccqrdrrlFmLGCwCtSwtL-pzZznZphZnpcNWSwGwVVPzrPrG-lgFllLLltgbDsrBCwrjWGmwmtw-MgJbDLlMQRJccchrhc-wbbjzZhdGDwLzZSBWqqHmZgssCWqFtMZ-VRJccfvPlTTlQlHQCWQhMMhCCHqQ-RlVfVJcPTVTfvvvJfNJVlcBjGjwhSLdBNGGnjLLBwzGb-bvpqHMVTTpZnqnWRQQQw-tfhFFdSFggfhbldhhZcnRscRcQmnRs-DPzgFJzFLfFbFSgPFgdPglMHpvBpHTCMGpjvMMpLvvNG-JggGLQgQpLpSPRJgGPSnGlFTDBjjRFvRjtBFjWvFjqRj-cmHhZcMHcWjrTBjrvm-dbHwdNNHhwTNThZHdlwQJJwngpgnJGnSPw-DbZjVfjVLhZDLpWPHpMZPmmGNp-lFcJJGcFqnBFqwJCHHMmNHPsdCNp-BlwccRQtBwBrwLGbGhGggzLgzR-RBhZPjlWqgbNbgGLBr-MzSmSzpFdHwpswzzHnzjnvLCbgtrtLGLbJLLJNtJtbwJ-MsSHdmMdpFfmFjpfcPWRhRVZfWQThZ-mqmssPCFhhsJccVg-FTttfwdjjHznJgfngpnc-dNFTjQNRtRNQldRNrRdHMRrlPZqCGlGBCqqZmmbPqDmDCmGW-ZJVRRZZJRcvmPhCJrvhm-PPWQDTfWbnnstlCGvjGrWMGMvr-TbbwddndsnsfDpwFqZFVHBVPqc-tFmpJmgJJgmFDWgRgFrrlGSltSQvZChMtCMM-TLcZHsjLVNBwGQCCGlsCShvh-nqNdwwccBwVLwjjDznZzppbgzFZfDF-qsTqCCCszjlqTssBShlQSSZFgZZhgB-LDPmVgDDJdLPrPgLgPZSFZQfhQGGBQJcSFJS-mvmVbVvtggVtvgdLVvtmptCsNTtjRnpRTTjpsqCp-BdNPLnmFvLFNgnmBmnFGnwSZZZWwqWgqjwWssTHWSS-bJhMzhbVMbDCcVpZtjHMqTMwtttSjH-hzclfCppVqQfbzQVbpzPQLNFBdrvdNGGBnmrmP-nLVLzBDJCCHqdLncqVJgSsDlGsbssmvvvbvbff-jMNHFWNTZZNwMPrPWrrPMMrrvSllbgsllfgbgvQsvGmglZbv-RjPjrjRPtNrwHhBtncCJtJtL-jbhhjhNjvqNbmjMjqhtCFdmPFdlzJzfFfJQJfR-GBBZWrZWgpSsnSngrrSgHzFzFFdClzfFQFlRZftQPR-TrGTrGWHpHWGHWVWsngprHpLbLLVvcqMcNbVNLhwVNbtNb-sQDvDmDLQFDRsdchzhBczLhhPhVz-MbGGMjjGZSjvfHvHSbfwBqcPnqqcPVhPNnqnzjcn-ZwMMHrWvSHbfJfTrbJwSMMfMsQDtsFRptlpdCRpWmptQDRmC-TwMHdcTznLqzTrHdzzzHTdgMRQWRhJhNjjvgQvQQWNjl-tbfsVbDCVSSDtSPQJWPvRNhQtghN-FVGBpGCVFCbfCbVbZCSHqmwqcqLcdHJGwHqqTd-lTlGfjLGwHNMggscsDRwsC-MrFtrzZZPZrtVQtnrrFdQhhDPDSphgDRhDcsCCgWpW-ZJmJVzVVJFHfGbqJGMLv-zsFZVjzlHPfTzGfLGt-mdrrmdMMcBcmNqNbPqfRDLPWPlqTWD-BNQhmmrBrQghgSmNBQQSmvwssjZZSJHljJFFHZJvZV-rLZCsZdMJfdNCsfZMrLdFmssnwgTRQgBBwgRwcngTNVRVQjV-StqDHlStDPgRTqcwjT-GlDGDhbpHhvSHWlzbWlhpzhJdrFLrCLmvdmFZsmJJjJfdv-pJHJMJsJjSMFdHhszFvMhlmmGNlSmmBGllWmVlwcTw-ZqZRDrZCZDtPDPDrCngrnnPQGVmGHVBWGWtGmWVwVlmTlGNl-ZQPgRqrrQPqLnrLMvLphHdvdjpJddb-NwbBjljFbcjtTcccqW-RHZrPHPpNgZTzTqc-sfrPdmPdpsmPPPrfQPVGlwGVBwbGVnFlNQCG-hQdNTlzhdTvrhdnTBqcWBLsBHgWQgBPg-zwzRDbDfqZBLHDLB-wFbFmjjRzfmjGGMGMfmJwwGCCnvNhpvSCNnrvJvCprnnSp-zshNNJbwGFJfGJzzzNRnHGnCnRHcRPgTmPmn-LMDVtZLStrrZClBrVDllLSBWRPTPPRRPmgWPVmPTPHTWgR-SDSqLMlrtLlLtrBqBdlMZjvffCNzwvhjvvzhdfNhvf-SLQmGBmhLSLQTBGBGwdwpJjwwQjwcVpJZJ-sNrWrWPNbHghrbgnNNzbWbFWdZpMpzVpdMZMzMMVZcwwJdwd-frrPNNWshWhhHDvDGDRSBSRvttqv-FJqpgvhJJRjFjZTqDsMHrzwjsSsSszMrMm-PPPQWGtnbbfBmPsFswwsMrcc-QfBtbldtWQfbWbnfGlFqZppvpFZZLhFlpq-ZqSMZHHCMpHTZTWmFTFZPZQJBgVGVJQvVVSDBvBtcBBG-RNsndwsNjsbsgGCgjQBttcBg-NRszRRNzLNNNwNfhCCrfdmTqFZllFFHFFpWhlTmWpq-llbbzDmSspGRpHpzsldzRRsVtFBBFJMMVVFLTTTMVtLTDM-cqgjqvNgvqCjQZqgGGnhMTnMJVLBLMtFhhVFWB-PfGGvQrPCjvjZgGCCCZZZbSmmmHlRpprlHrHwssSRr-mRmpFpWpfMMgLnmS-CdCsqzdRzqStLjSqfMnL-wQRHdTzCQbzCwsTrZBlFZGpVlpFGQD-qnMTnTVSTPTHTHcMZMvVpmppmFmVzFLLFLlFpG-gBjDsjRRwhDDghthwwWZwLmpmwWWLWLbGZ-NhZtZtBgPTNJJNTS-jLjjmpHvzvZrfzQjmfHHWrfbqblLsSlTsqsgqPJbPqVglb-FBcCwDwtwgcgnCwcGchtJSsRqVRVJPPqDlbSDRPq-MBhthFNtMGCwhcwnpQfWjNrQprpvzpgQ-RfCnWfnhCbwHgWjzBgzB-PsVqDsSTshsgszpsph-DPDvTVtTShhSZhmqSvLlQJFnQJJZnbCnlCCZ-pRRdJngltnwwvTNSWqWffqgBqD-HQGcsdrjzMDDBfGMGG-FLhsdbzCLLHjhntpVnRPRvZV-gZNwQHHNRlGvhvhGRvRb-dpSSBDrzdCfcSzfrzZrfCfMbthWWWPttDthvMFWvvvPj-ZdpBpZCrssBJZfSJBzBdCTcnmQwmnVVlmqTQTTQlHLwNnN-ssCpTttVVVpzZDVvRpCsRtDgWBWBBFBJvvJHMBghGghrMJ-lwLmNNLwSblbmSQLfhJHZgHrHhhJJhHHmW-QLSdbdPqndlNlLdSLNQncpRtRTcRVTPPZRCjVCcc-wzzJclzcTThvWSSCqRlQSsNN-rDpVjpVVDpsQSRDRfQmm-GLbjrLpFbgLVLLgdbjVpchcFZhvBwJvtvtJcZwRB-wPgZgLVMfWVTgmTZZZftJjtfjtJCcdpjdCqc-zGGbQQnQGvBBhGQvvvBBSBvQdhdqqCpdddDmJlCcDjCtJdmJ-HszzHBzQBSmGSwTWgswZPWTVgZ-GDFvzCFdrszSdNJrFfjjfqZjRfsjpqmcwZ-WbbVtVnBPWMgBLMBnQQnBQHcjfjpZRwqcwMfcNTZRqqNmT-WQQnVVPHtggLghWWhHnPVQbvlJhSlrvJDlFGJDdDCzGNFF-dVhTBjBHtTVqWRJZRqhJZQ-brSDTbDfcCwDzfCSbwMQnlqCRJnMgWWnZngM-DFwNSrwNwbDzbFTTFtjmBpVdGpHs-dPQfdfTzDrFDmFDBgBFj-RlJRclcswJRvnwPcpjbjbbCZjFjbBmsbFZ-pqncGlcRJpHGpllGHhvPhRTHrQrttVVfrdQzfrTdftfV-RCzTzRMTfCfRRDzRfhSmZZlCslBbZZBVtZBZsqBL-nvvJPpdcFnPcWnFnVZvBqVlZMbZBNVlV-FpWPMdjdPhSTmwfSjD-NDJjNHLLNWjcLLWCLJLZjLDtRqqtgtMqgtqnRqnSRgggtZ-BwrlfFwmQwhwfPBFhsBdFmbQggCgqQVtbRSqttqMngnp-llPPwsPlGshBJGWJLcHvCzNv-rBvTmwdTSbnrvVWsWVftGfJQGT-gNRLLjlPRWnFVRFDFW-lpCpPNZqZCdvdppnSnBr-ShRdCrJgHClZJtZDGMMz-LvqVVTTNbVPLQNFTnwwMtzFZGDDwmtnM-VLbNvpPvTNVqVbbNpbVPGNLPrRWrcRCWdSrCjWSHcHSdWpCh-tNmZnLSZPFLDnLTmhJMWczQdhmWhWH-bGqbgrpsCsWhcChNQfJz-vwlNbppsRGRRSSSDvjTjLZjZ-zgMZhgfBtftSZQQmLHpSWH-cdqcqnrJVGjjqPVjrPnfpJmsQHQQpsSsbsSDmm-NNnrNqNlrNcPTlBvBvgggfMv-llPrrLHBHCrRRBjrHCjBdrPmvJZzZgZbmgJlZmZhMhhmvh-pNDstVtNtGFNSDFScQtfwzzFJwmJhgqzbMwqZJmh-fpNsptGtQcTsSTccprddCWPrWdTRBMMCMd-TTtDVqTsTcJFgbCqmbCq-NWZQnllzfBFZPBGWQGzFPFRNNgHbHrrwbNrmCbggJRHR-nBZjGFjMQBMPZnjfWjstpcctttvVtcTttMpL-qphVCCwnHqhnRVznFwvLtBTLDTWZtwLWWS-JmdlsdlsjfJfrtjTcvtctDZSSB-rsmfPGbrPbPJfPmrsgMrdJdlFTHhFCqhNqVHnNHHCFznhphG-JsWFMJJzrhSSdFdldmmdmdQc-qLLgCVTgLbBvqsQPVdQGcRRmQmdc-bBCBgCCDbLDqTvqqjpShHfzrzMfjtHHSHsfz-nvFSBFlvvgQFFBzQnlQglmRRzqwsrrMJJMrsMqrfrwzf-CjZNCNhLDNbPZZLZZhwVjpcfrqRhsdJqdsshRTTdqJrJ-jNNDDppjpjDWNVLCVVDpGVVPBFtlSQFWvvQvSSQHSgwQnvtB-WhrQWBRWwhzgmpnSpH-LqMVsJVvFMJLJMsfNjsTJvCgFbSmzgpSHzmngHbGPCbm-jvMjjtqVjTRnwZQwBWwt-jfTWSGSTTWhgcngQfbtJfNzztBQBzz-pVVwsdppRVPLVmPsVVHsjPLPzQdzBzQFzFBNNrJZZQBzbbFF-VmsqHmjHmpvGDSWDvlclSl-PNZfTFSFfTFGCHqqmbFm-WjzRWrjVgnjzplrWWjJVppgGPGsgstmPCCtcmssQqGQt-pzjzJVvnzJjWvpPlnVRVrvnlTDLNNhwfdNZLfMZLwLhTNvTw-QFrQZMFVrVpVszzcNTdMRCCb-SvljGmlvLfwLhLLLHlHdNzsRthhbbRccRCRNbC-LfwlDmlvGBSjjlLLgpPpFJqgQndQgZBJ-RBjPRHdjPfqQcfhcdv-SngFcJZJlcnctSlhhsQvGsDGDsDnfs-pSmFgSWNJFNtStrmNtpCCjPVcbjjHbcWTBHBHL-vGjqCPqNPGFGNftLwmZwfQNTLp-hrdBCSHcCJJcCBShJswmLQpLbbQZTLLJmmZp-BdHHSzrBWdzchzzCcdzHddcDVWFnjPjllGggVlWljPFFFWPM-hBtZZnpbhbPZJbnhDtPnpBtpfjfNNzrrCzjFzFzFTjfjjWzJ-gHllMqRSmqcqMTdggMqHlcFzRrFQWNfvrRvzQrWjWvWf-gwqlgHmmdsgwlwMHZtpsbBbtDBThbBht-CsDLFFLFCvczsCsJrCrJJLRgbQQgmMmPbDDQbPnMgMmg-VlwNBNVhjNVNWBwWjtbRMRZzPmQnfQMPnlZP-VWWSSwGTwtwWWNVwwpqJJrcJGvzqCJCqJF-wLwSSbzwCvddlvvlSj-THnQnnHttcvpQzrZRllZ-sTntBHTnVbPbgzsbgL-FwHgrHvFQQwpHhNhTBLdpNNNLd-fCGqCVtszfSslCSzSGsfCssjNTqLTdmjNLBLdnTTTMTjTg-DccfslfgRSSVVzlcSVtzDRVHwQZFrwwvwFWbbbRRWwrFJb-CwwWwwFNRpFFpZQHtsmfqbQDTQTTqb-VcjzLjGjzGjGjVjLdzqmDqHrsmsqGRrHqGqH-RjdVlgdnljlBnSgPCpNwwMWwMM-tCCtqtbPGzsSQVzQTq-mzMmHMpRsRQTsFFV-DpzDwgdMzMLppNmNpDpfgrbhLcGtPrbtrbrbhnbBcC-BvsQBBBLvDQGjDvSQLTvrHprHlRpVlVllgRbRbHPqq-MMMMCpfJFZZMmCzwpVPCWRtHgqWgqClgtt-FwzmfzhFFdFcpvSDSBDThs-fQrGQbFFFrHHtlHPclzzPLvc-mTnwpNCCqMqjmCThpTpSvvtBczstlLznvsztsPPP-mCpTNhmmpCqCmjmpTjmLCpSJQZVfFVrDVfffFFgfgJQFdbgG-GmWjRBSfttcGfRcSclVVJqsTMllsgJVMVZwV-pPFNpfNCdNzCVMTTNqVssqJN-dzPfHCLLhdjjLGRnmnmr-GPhPfGWgggfslffPsVPGsqJMzLQJtBprwQJJGQwLpQrw-ZNdmvbDDbNvHbmZCcJQwMmzMwWWQrrwttp-bvdDNdnvNbnHDdnDHHRSbnqhqhWfjWFVTVhRVjfjFTfP-hTThfWNCDRfsVCDhpgzgbpPZZwbnZQns-GSjGGcCBGmdjdSlGBcmZwzJzpPpJzwPwQbzgPd-BGmcrcStcMMMmrSLmSMCvFVRFDhfFhhNDWWTqFqTvf-ZmjDTTbmqQCCQQSwvhsL-FGVJPmPmtRVRsCvvRLwwhC-JgdHJgmfbjzTpTMf-fTbsVCsssgLNrfNrgm-zQvzZlRvddvpNLpZrMNNLZ-HLvWFHHlFQvzHnnlnvQqhzWvstBwbGVtstjGqjjwqGGCcwGq-JNpNdzzdJhNnfNGBZLqZqlhvSZSG-QswtcmmwwmTmwwcwZSLlZLDSvSvlBZQD-FsVFBbFgFsPwtVBTwgTPcsmpzdNngfzfpCzJdzCJzNCndn-qcvrLBppgpWWWgLcpzPfhNDqdzqwDDzwhV-MZFjFnHFMHbMntMtnwStfddPhDffDfzDfS-QmnjMZnlHjmnMGFnFlMmjlZWzLgsGgcrspBBLCBcgvgBRC-sdfWHjZfrZrSPMCQ-zqtWRDDDRMbrQJPQ-zwhwzmqwzmFpWzvFqBmFvjNHlHfgVLBgdfVfNVjLsl-lRlBTlvlZfhtbGBWtFBz-cqCNjjqjrNrcNjwDqNPCVrSQStSWshFhtQhbQzGzmFCG-HjPPzMcdNqjcNHMqPjdpgpZflfdgnTfdlvlJ-VpwQJVRtHplnnwtppHhqWBCfVdNNPqPBPWsBDq-jzLZCrvvrZjZvqNffvDNDcWDWd-LTrZZLFZbgTzgjZZjFClJhTHTplQpmnQlpmpQR-JGJnSWLGSpWHVHwGGJHpZdwPdTTPMdTMDdlzccPMPv-gqrrmtbrbgggqgBtqmRSrFgNCzvMDvlMPDdddvzBcPMMMDBd-gjrmRgmtRggFtqjbhgbjrtnJJHWLHQWZZLhZsLLGHhSL-BtTDNggLRPdWQHqggg-wrVpVVlCJVGMMJVdHWSdPSqqRwSQSP-vCVrpvvGjlphBRmZBhmBhBND-lqDcZGcSSqSqbDnccSLJgHgLRfnvvJRLmvWJ-FVCFPChQzVhmsFBgddRgJBfdNfJdfv-FzCpmTQzjQCThppTSttqDccMTDGcDG-QCSGBGCrCsMBTCQwMGSfvvLNNnnVLDlNVNDdVdlr-ZHtPffjWbqgtmnNdvljFnFhdVv-JRWbmgmRJtmJMGGwSBBRRRfQ-LqNrCfCQQhtgnPnc-JWBrWrVlbWgbbtcb-VwvTBprdrVJVNLNMNNqfqpjN-bjVqdHrdqVHPsPNbqHbqNdjFGRwRGlttRtMtRtFFGMLHJw-cfSpZnBZWQBZJlGRJJcwGMGL-WWBhTMgDTZghVjgjssbrbddd";
//totalPriorites(temp);